import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, {useState, useEffect, useRef, useMemo} from "react";
import io from "socket.io-client";
import styles from '../styles/Home.module.css'

interface ChatMessage {
  user: string;
  message: string;
}

const Home: NextPage = () => {

  const [message, setMessage] = useState('');
  const [messages, setMessages] = useState([]);
  const socket = useMemo(() => io(), []);

  useEffect(() => { socketInitialize() }, []);

  const socketInitialize = async () => {
    await fetch('/api/socketio');
    socket.on('connect', () => {
      console.log('connected');
    });
    socket.on('receivedMessage', (receivedMessage) => {
      console.log(receivedMessage);
      messages.push(receivedMessage);
      setMessages([...messages]);
    });
  }

  const handleSendMessage = () => {
    if(!message || !message.trim()) return;
    socket.emit('message', message);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Chat Room</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='chatMessages'>
          <ul>{
            messages.map((msg) => {
              return (
                  <li>{msg}</li>
              );
            })
          }</ul>
        </div>
        <div>
          <input
            type='text'
            className='chatInput'
            placeholder='Enter a message'
            value={message}
            onChange={(e) => {setMessage(e.target.value)}}
          >
          </input>
          <button onClick={handleSendMessage}>
            Send
          </button>
        </div>
      </main>
    </div>
  )
}

export default Home
